### ISSUE TITLE
Don't require running of simulation to access/edit stage components in embed feature 

### ISSUE THREAD

**Issue by nikkihutchins** [c2stem/snap-physics#1]
When we use embed (only shows stage in iframe) it currently requires students to click on a green flag to run the simulation once before they can edit components (such as material squares in SPICE). Can we eliminate that feature? 

Reason: running the simulation saves data in design/test history and impacts data tools

**Comment by NaveedMohammed** [comment]
Added a new URL flag to remove overlay a419bba3057ba87d31c8537ff604b6d5c6455b71
